### ISSUE TITLE
Missing variables when using nested mixins

### ISSUE THREAD

**Issue by florin555** [jannishuebl/orchparty#22]
For the following input:
```
  mixin 'm1' do
    variables do
      var my_var: 'hello'
    end
  end

  mixin 'm2' do
    mix 'm1'
    environment(MY_VAR: -> { my_var })
  end

  mixin 'm3' do
    mix 'm2'
  end

  service 'service_a' do
    mix 'm2'
  end

  service 'service_b' do
    mix 'm3'
  end
```

I am getting the following output

```
service_a:
  environment:
    MY_VAR: hello
service_b:
  environment:
    MY_VAR:
```

Both services should be identical, but in `service_b` the value of MY_VAR is missing.
